name: flyin
description: "A mobile app with social video sharing functionalities."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  miniplayer: ^1.0.1
  timeago: ^3.6.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  firebase_storage: ^11.6.10
  permission_handler: ^11.3.0
  uuid: ^4.3.3
  firebase_app_check: ^0.2.1+19
  firebase_database: ^10.4.11
  cloud_firestore: ^4.15.10
  geolocator: ^11.0.0
  appinio_video_player: ^1.3.0
  video_player: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


# APP ICON
flutter_icons:
  image_path: assets/images/app_logo.png
  android: "launcher_icon"
  ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/images/app_logo.png
    # - assets/icons/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-light.ttf
          weight: 300

